### ISSUE TITLE
Issue running python AzuriteVisualizer.py 

### ISSUE THREAD

**Issue by bsc-lcuevas** [mwrlabs/Azurite#7]
Running the Visualizer against the vm JSON I get:
[*] Parsing data...
Traceback (most recent call last):
  File "AzuriteVisualizer.py", line 483, in <module>
    main()
  File "AzuriteVisualizer.py", line 480, in main
    parseJson()
  File "AzuriteVisualizer.py", line 43, in parseJson
    for vnet in data['subscriptionVNETs']:
TypeError: list indices must be integers, not str

Running against the subscription JSON I get:

Version: 0.6 Beta
Author: Apostolos Mastoris (@Lgrec0)
Email: apostolis.mastoris[at]mwrinfosecurity.com

[*] Parsing data...
Traceback (most recent call last):
  File "AzuriteVisualizer.py", line 483, in <module>
    main()
  File "AzuriteVisualizer.py", line 480, in main
    parseJson()
  File "AzuriteVisualizer.py", line 55, in parseJson
    vnetNode['label'] = data['subscriptionVNETs']['vnetName']
TypeError: list indices must be integers, not str

I am on Windows 10 running from cmd.

**Comment by masonww** [comment]
Was a solution to this ever found?

**Comment by pwnf** [comment]
Still an issue in 2023..
